export const countries = [
  "Albaniya",
  "Almaniya",
  "Amerika Birləşmiş Ştatları",
  "Amerika Birləşmiş Ştatları Virgin Adaları",
  "Amerika Samoası",
  "Andorra",
  "Anguilla",
  "Anqola",
  "Antiqua və Barbuda",
  "Argentina",
  "Aruba",
  "Avstraliya",
  "Avstriya",
  "Azərbaycan",
  "Baham adaları",
  "Banqladeş",
  "Barbados",
  "Belarus",
  "Belçika",
  "Beliz",
  "Benin",
  "Bermuda",
  "Bəhreyn",
  "Birləşmiş Ərəb Əmirlikləri",
  "Birləşmiş Krallıq",
  "Birma (Myanma)",
  "Boliviya",
  "Bolqarıstan",
  "Bosniya və Herseqovina",
  "Botsvana",
  "Braziliya",
  "Britaniya Virgin Adaları",
  "Bruney",
  "Burkina Faso",
  "Burundi",
  "Butan",
  "Cəbəllütariq",
  "Cənubi Afrika",
  "Cənubi Koreya",
  "Cənubi Sudan",
  "Cibuti",
  "Çad",
  "Çexiya",
  "Çili",
  "Çin",
  "Çin, P.R.: Honq Konq",
  "Çin, P.R.: Makao",
  "Danimarka",
  "Dominika",
  "Dominikan Respublikası",
  "Efiopiya",
  "Ekvador",
  "Ekvatorial Qvineya",
  "El Salvador",
  "Eritreya",
  "Ermənistan",
  "Estoniya",
  "Esvatini",
  "Əfqanıstan",
  "Əlcəzair",
  "Farer adaları",
  "Fələstin",
  "Fici",
  "Fildişi Sahili",
  "Filippin",
  "Finlandiya",
  "Fransa",
  "Fransız Polinezyası",
  "Gürcüstan",
  "Haiti",
  "Hindistan",
  "Hollandiya",
  "Honduras",
  "Xorvatiya",
  "İndoneziya",
  "İnsan Adası",
  "İordaniya",
  "İraq",
  "İran",
  "İrlandiya",
  "İslandiya",
  "İspaniya",
  "İsrail",
  "İsveç",
  "İsveçrə",
  "İtaliya",
  "Kabo Verde",
  "Kamboca",
  "Kamerun",
  "Kanada",
  "Kanal Adaları",
  "Kayman Adaları",
  "Keniya",
  "Kipr",
  "Kiribati",
  "Kolumbiya",
  "Komor",
  "Konqo Dem. Rep.",
  "Konqo Respublikası",
  "Kosovo",
  "Kosta Rika",
  "Kuba",
  "Kurasao",
  "Küveyt",
  "Qabon",
  "Qambiya",
  "Qana",
  "Qayana",
  "Qazaxıstan",
  "Qətər",
  "Qırğızıstan",
  "Qrenada",
  "Qrenlandiya",
  "Quam",
  "Qvatemala",
  "Qvineya",
  "Qvineya-Bisau",
  "Laos",
  "Latviya",
  "Lesoto",
  "Liberiya",
  "Lixtenşteyn",
  "Litva",
  "Livan",
  "Liviya",
  "Lüksemburq",
  "Macarıstan",
  "Madaqaskar",
  "Malavi",
  "Malayziya",
  "Maldiv adaları",
  "Mali",
  "Malta",
  "Marşal Adaları",
  "Mavrikiy",
  "Mavritaniya",
  "Meksika",
  "Mərakeş",
  "Mərkəzi Afrika Respublikası",
  "Mikroneziya",
  "Misir",
  "Moldova",
  "Monako",
  "Monqolustan",
  "Monteneqro",
  "Montserrat",
  "Mozambik",
  "Müqəddəs Taxt (Vatikan)",
  "Myanma",
  "Namibiya",
  "Nauru",
  "Nepal",
  "Niger",
  "Nigeriya",
  "Nikaraqua",
  "Norfolk Island",
  "Norveç",
  "Oman",
  "Özbəkistan",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Yeni Qvineya",
  "Paraqvay",
  "Peru",
  "Polşa",
  "Portuqaliya",
  "Puerto Riko",
  "Ruanda",
  "Rumıniya",
  "Rusiya",
  "Samoa",
  "San Marino",
  "Sao Tome və Prinsipi",
  "Seneqal",
  "Serbiya",
  "Seyşel adaları",
  "Səudiyyə Ərəbistanı",
  "Sierra Leone",
  "Sinqapur",
  "Sint Maarten (Hollandiya hissəsi)",
  "Slovakiya",
  "Sloveniya",
  "Solomon adaları",
  "Somali",
  "St. Kitts və Nevis",
  "St. Lucia",
  "St. Martin (Fransız hissəsi)",
  "St. Vinsent və Qrenadinlər",
  "Sudan",
  "Surinam",
  "Suriya",
  "Şimali Koreya",
  "Şimali Makedoniya",
  "Şimali Mariana Adaları",
  "Şri Lanka",
  "Tacikistan",
  "Tanzaniya",
  "Tayland",
  "Tayvan",
  "Timor-Leste",
  "Toqo",
  "Tonqa",
  "Trinidad və Tobaqo",
  "Tunis",
  "Turks və Kaykos Adaları",
  "Tuvalu",
  "Türkiyə",
  "Türkmənistan",
  "Ukrayna",
  "Uqanda",
  "Uruqvay",
  "Vanuatu",
  "Venesuela",
  "Vyetnam",
  "Yamayka",
  "Yaponiya",
  "Yeni Kaledoniya",
  "Yeni Zelandiya",
  "Yəmən",
  "Yunanıstan",
  "Zambiya",
  "Zimbabve",
];
