export const specialities = [
  "Aerokosmik informasiya sistemləri",
  "Aerokosmik monitorinq",
  "Aerokosmik mühəndislik",
  "Aeronaviqasiya təminatı",
  "Aktyor ifaçılığının tarixi və nəzəriyyəsi",
  "Aktyor sənəti",
  "Akvabıtkilər",
  "Aqrar istehsalatın avtomatlaşdırılması vasitələrinin istismarı, təmiri və servis xidməti",
  "Aqrar istehsalatın elektrikləşdirilməsi",
  "Aqrar istehsalatın mexanikləşdirılməsi",
  "Aqrar istehsalatın texniki təminatı",
  "Aqrar sahədə ətraf mühitin mühafizəsi",
  "Aqrar sahənin iqtisadiyyatı",
  "Aqrobiotexnologiya",
  "Aqrogeobotanika",
  "Aqrokimya",
  "Aqromühəndislik",
  "Aqronomluq",
  "Analitik kimya",
  "Antropologiya",
  "Arxeologiya və etnoqrafiya",
  "Arxeologiya və etnoqrafıya",
  "Arxeoloji və tarixi memarlıq",
  "Arxiv işi və arxivşünaslıq",
  "Asiya və Afrika ölkələrinin tarixi",
  "Aşıq sənəti",
  "Atom və molekul fizikası",
  "Aviasiya cihazları",
  "Aviasiya meteorologiyası",
  "Aviasiya təhlükəsizliyi mühəndisliyi",
  "Avropa hüququ",
  "Avropa və Amerikanın yeni və ən yeni tarixi",
  "Avtomatlaşdırılmış elektrotexnoloji qurğular və sistemlər",
  "Azərbaycan dili",
  "Azərbaycan dili və ədəbiyyatı müəllimliyi",
  "Azərbaycan dili və ədəbiyyatının tədrisi metodikası və metodologiyası",
  "Azərbaycan ədəbiyyatı",
  "Azərbaycan tarixinin mənbəşünaslığı",
  "Azərbaycanda siyasi proseslər",
  "Azərbaycanın fiziki coğrafiyası",
  "Azərbaycanın xarici iqtisadi əlaqələri",
  "Azərbaycanın qədim və orta əsrlər tarixi",
  "Azərbaycanın yeni və ən yeni tarixi",
  "Bağçılıq və tərəvəzçilik",
  "Balet tarixi",
  "Balet tənqidi",
  "Balıqçılıq",
  "Balıqçılıq təsərrüfatı işi",
  "Bank işi",
  "Baytarlıq cərrahiyyəsi",
  "Baytarlıq əczaçılığı",
  "Baytarlıq təbabəti",
  "Baytar-sanitar ekspertizası",
  "Beynəlxalq hüquq",
  "Beynəlxalq iqtisadi hüquq",
  "Beynəlxalq iqtisadi münasibətlər",
  "Beynəlxalq jurnalistika",
  "Beynəlxalq maliyyə və valyuta kredit münasibətləri",
  "Beynəlxalq mədəni əlaqələr tarixi və nəzəriyyəsi",
  "Beynəlxalq münasibətlər",
  "Beynəlxalq münasibətlər tarixi və nəzəriyyəsi",
  "Beynəlxalq münasibətlər və diplomatiya",
  "Beynəlxalq ticarət və logistika",
  "Beynəlxalq turizm və ölkəşünaslıq",
  "Bədən tərbiyəsi və idmanda",
  "Bədən tərbiyəsi və idmanda tibbi-bioloji təminat",
  "Bədii yaradıcılıq və ekran dramaturgiyası ",
  "Bərk cisim kimyası",
  "Bərk tullantıların emalı texnologiyası",
  "Bərpa olunan enerji mənbələri",
  "Bəstəkarlıq",
  "Biblioqrafik ehtiyatların yaradılması və istifadəsi",
  "Biblioqrafıyaşünashq",
  "Biliklərin əldə edilməsi sistemləri",
  "Biofizika",
  "Biokimya",
  "Biologiya",
  "Biologiya fənninin tədrisi metodikası və metodologiyası",
  "Biologiya müəllimliyi",
  "Biologiya və kənd təsərrüfatının əsasları",
  "Bioloji sistemlər fizikası",
  "Biotexnologiya",
  "Bitki anatomiyası və morfologiyası",
  "Bitki fiziologiyası",
  "Bitki mühafizəsi",
  "Bitkiçilik",
  "Bitkiçilik məhsullarının saxlanması və emalı texnologiyası",
  "Bitkilərin genetikası və seleksiyası",
  "Bitkilərin genetikası və seleksiyası ",
  "Bitkilərin xəstəlikdən və ziyanvericilərdən mühafizəsi",
  "Bitkilərin karantini",
  "Bitkilərin mühafizəsi",
  "Bitkilərin seleksiyası",
  "Bitkilərin toxumçuluğu",
  "Biznes inzibatçılığı",
  "Biznesin idarə edilməsi",
  "Biznesin təşkili və idarə edilməsi",
  "Botanika",
  "Cəbr və topologiya",
  "Cihaz mühəndisliyi",
  "Cinayət hüququ, cinayət prosesi,kriminalistika və məhkəmə\nekspertizası",
  "Coğrafiya",
  "Coğrafiya fənninin tədrisi metodikası və metodologiyası",
  "Coğrafiya müəllimliyi",
  "Daxiliyanma mühərrikləri və onların texniki istismarı",
  "Davamlı inkişafda insan potensialı",
  "Davamlı inkişafda təbii ehtiyatların idarə edilməsi",
  "Davamlı inkişafın idarə edilməsi",
  "Dekorativ sənət",
  "Dəmir yolu nəqliyyatında avtomatika,telemexanıka və rabitə",
  "Dəniz naviqasiyası mühəndisliyi",
  "Dəniz və enerji hüququ",
  "Dəniz və okean dibinin geologiyası",
  "Diferensial tənliklər",
  "Dil və ədəbiyyat müəllimliyi",
  "Dil və ədəbiyyatın tədrisi metodikası",
  "Dil və ədəbiyyatın tədrisi metodikası və metodologiyası ",
  "Dilşünaslıq",
  "Dinamiki arxitekturalı multiprosessor sistem və şəbəkələri",
  "Dinin fəlsəfəsi",
  "Dinin psixologiyası",
  "Dinin sosiologiyası",
  "Dinlərin tarixi",
  "Dinşünashq",
  "Dirijorluq",
  "Dizayn",
  "Dizayn və texniki estetika",
  "Dövlət hüququ",
  "Dövlət informasiya sistemlərinin təhlükəsizliyi",
  "Dövlət qulluğunun təşkili və idarə olunması",
  "Dövlət proqramlarının və layihələrin olunması",
  "Dövlət strukturlarında menecment",
  "Dövlət və bələdiyyə idarəetməsi",
  "Dövlət və hüquq nəzəriyyəsi və tarixi",
  "Dövlət və ictimai münasibətlər",
  "Dünya siyasəti",
  "Dünya siyasi prosesləri",
  "Dünya və Azərbaycan kitabşünaslığı",
  "Ekologiya",
  "Ekologiya mühəndisliyi",
  "Ekoloji biologiya",
  "Ekoloji kənd təsərrüfatı",
  "Ekoloji kimya",
  "Ekoloji kimyəvi monitorinq",
  "Elektrik aparatları",
  "Elektrik nəqliyyatı",
  "Elektrik şəbəkə və sistemləri",
  "Elektrik təchizatı",
  "Elektrik təchizatının optimallaşdırılması və modelləşdirilməsi ",
  "Elektrik və elektronika mühəndisliyi",
  "Elektroenergetika",
  "Elektrokimya",
  "Elektron cihazlar və qurğular",
  "Elektron idarəetmə",
  "Elektronika və avtomatika",
  "Energetika mühəndisliyi",
  "Enerji maşınlarının istehsalı",
  "Entomologiya",
  "Epizootoİogiya və infeksion xəstəliklər",
  "Etnologiya",
  "Etnomusiqişünaslıq",
  "Farmakoqnoziya",
  "Faydalı qazıntı yataqlarının işlənməsi",
  "Faydalı qazıntıların zənginləşdirilməsi",
  "Fəlsəfə",
  "Filiz və qeyri- filiz faydalı qazıntı",
  "Filologiya",
  "Fizika",
  "Fizika fənninin tədrisi metodikası və metodologiyası",
  "Fizika müəllimliyi",
  "Fiziki kimya",
  "Fiziki tərbiyə nəzəriyyəsi və metodikası",
  "Fiziki tərbiyə və çağırışaqədərki",
  "Fizioterapiya və tibbi reabilitasiya",
  "Fövqəladə hallarda texnoloji proseslərin təhlükəsizliyi",
  "Fövqəladə halların idarə olunması",
  "Genetika",
  "Geokimya",
  "Geologiya",
  "Geologiya və geofizika mühəndisliyi",
  "Geomatıka",
  "Geomatika və geodeziya mühəndisliyi",
  "Gəmi energetik qurğuları və onların istismarı",
  "Gəmi energetik qurğularının istismarı mühəndisliyi",
  "Gəmi təmiri",
  "Gəmiqayırma",
  "Gəmiqayırma və gəmi təmiri mühəndisliyi",
  "Gəmilərin elektroenerji sistemləri",
  "Gəmilərin hərəkətinin idarə edilməsi",
  "Gənclərlə iş",
  "Gömrük ekspertizası",
  "Gömrük işi",
  "Hava gəmilərinin uçuş istismarı",
  "Hava nəqliyyatı hərəkətinin idarə cihaz avadanlıqları",
  "Hava nəqliyyatında texnoloji proseslərin və istehsalatın təhlükəsizliyi",
  "Hava nəqliyyatının hərəkətinin təşkili",
  "Hesablama riyaziyyatı",
  "Heyətin idarə edilməsi",
  "Heykəltəraşlıq",
  "Heyvandarlığın mexanikləşdirilməsındə texnoloji proseslər və aparatlar",
  "Həndəsə",
  "Hərbi kompozisiya materialları mühəndisliyi",
  "Hərbi rabitə vasitələri mühəndisliyi",
  "Həyat fəaliyyətinin müxtəlif mühəndisliyi",
  "Həyat fəaliyyətinin təhlükəsizliyi mühəndisliyi",
  "Hidrogeoekologiya",
  "Hidrogeologiya",
  "Hidrometeorologiya",
  "Hüquq psixologiyası",
  "Hüquqşünaslıq",
  "Xalq çalğı alətləri ifaçılığı",
  "Xalq çalğı alətləri ifaçılığının",
  "Xanəndəlik",
  "Xarici dil müəllimliyi",
  "Xarici dilin tədrisi metodikası və metodologiyası",
  "Xarici dilin tədrisi və metodikası ",
  "Xidmət sferasında mühasibat uçotu və audit",
  "Xoreoqrafiya sənətinin tarixi və nəzəriyyəsi",
  "İaşə məhsullarının texnologiyası və iaşənin təşkili",
  "İbtidai sinif müəllimliyi",
  "İbtidai sinifdə tədrisin metodika və metodologiyası",
  "İctimai səhiyyə",
  "İctimai siyasət",
  "İdarəetmədə informasiya sistemləri",
  "İdarəetmənin informasiya texnologiyaları",
  "İdarəetmənin sosiologiyası",
  "İdman menecmenti və kommunikasiya",
  "İdman məşqinin nəzəriyyəsi və metodikası",
  "İxtiologiya",
  "İqlimşünaslıq",
  "İqtisadi fəaliyyətin riyazi və informasiya təminatı",
  "İqtisadi informasiya sistemləri",
  "İqtisadi informatika",
  "İqtisadi kibernetika",
  "İqtisadi nəzəriyyə",
  "İqtisadi və sosial coğrafiya",
  "İqtisadiyyat",
  "İqtisadiyyatın hüquqi tənzimlənməsi",
  "İqtisadiyyatın tənzimlənməsi",
  "İncəsənət əsərlərinin bərpası və ekspertizası ",
  "İnformasiya hüququ",
  "İnformasiya işlənməsinin və idarəetmənin avtomatlaşdırılmış sistemləri",
  "İnformasiya mühafizəsi və təhlükəsizliyi",
  "İnformasiya sistemləri",
  "İnformasiya texnologiyaları",
  "İnformasiya texnologiyaları və telekommunikasiya sistemləri",
  "İnformasiya təhlükəsizliyi",
  "İnformatika",
  "İnformatika fənninin tədrisi",
  "İnformatika müəllimliyi",
  "İnnovasiya strategiyasının işlənməsi",
  "İnnovasiyaların və layihələrin idarə olunması",
  "İnsan genetikası",
  "İnsan hüquqları",
  "İnsan və heyvan fiziologiyası",
  "İnstrumental ifaçılığın tarixi,nəzəriyyəsi və metodikası",
  "İnstrumental ifaçılıq",
  "İnşaat mühəndisliyi",
  "İnteqrasiya olunmuş və kompüterləşdirilmış dəzgah sistemləri",
  "İntellektual sistemlər",
  "İnvestisiyanın iqtisadi qiymətləndirilməsi",
  "İnzibati hüquq, inzibati proses,iqtisadi və maliyyə hüququ",
  "İpəkçilik",
  "İslamşünaslıq",
  "İstehlak mallarının keyfiyyət ekspertizası",
  "İstehsal sferasında mühasibat uçotu və audit",
  "İstehsalat və xidmət sahələrinin",
  "İstilik elektrik stansiyaları",
  "İstilik fizikası və molekulyar fizika",
  "Jurnalistika",
  "Jurnalistika nəzəriyyəsi",
  "Kabel və keçiricilərin fizikası və texnikası",
  "Keyfiyyətə nəzarət, diaqnostik üsul və sistemlər",
  "Kibertəhlükəsizlik",
  "Kimya",
  "Kimya fənninin tədrisi metodikası və metodologiyası",
  "Kimya müəllimliyi",
  "Kimya mühəndisliyi",
  "Kimya və biologiya müəllimliyi",
  "Kimyəvi ekspertiza",
  "Kimyəvi kınetika və kataliz",
  "Kino tarixi və nəzəriyyəsi",
  "Kino tənqidi",
  "Kinooperator sənətinin tarixi və nəzəriyyəsi",
  "Kitabxanaçılıq və informasiya fəaliyyəti",
  "Kitabxana-informasiya texnologiyası",
  "Kitabxanaşünaslıq",
  "Klinik psixologiya",
  "Kolloid kimya",
  "Kommersiya hüququ",
  "Kommunikasiya sistemləri mühəndisliyi",
  "Kommunikasiya və rəqəmsal media",
  "Kompozisiya materialları",
  "Kompozisiya materialları kimyası",
  "Kompüter elmləri",
  "Kompüter elmləri və texnologiyaları",
  "Kompüter mühəndisliyi",
  "Kompüter sistemləri və şəbəkələri",
  "Kompüter sistemlərinin və şəbəkələrinin proqram təminatı",
  "Kompüter texnikasının layihələndirilməsi və konstruksiya edilməsi",
  "Kompüter təhlükəsizliyi",
  "Kompüterli modelləşdirmə",
  "Konfliktologiya",
  "Korreksiyaedici təlim",
  "Kosmik aparatlar və idarəetmə sistemləri",
  "Kristalloqrafiya və kristal kimyası",
  "Kvant elektronikası",
  "Qafqaz xalqlarının tarixi",
  "Qaynaq istehsalı metallurgiyası,texnologiyası və avadanlığı ",
  "Qeyri- ərzaq məhsullarının ekspertizası və marketinqi",
  "Qeyri- üzvi kimya",
  "Qeyri-üzvi kimya",
  "Qədim dünya tarixi",
  "Qida mühəndisliyi",
  "Qida təhlükəsizliyi",
  "Qiymətləndirmə",
  "Qoyunçuluq",
  "Qrafika",
  "Qurğular nəzəriyyəsi",
  "Quşçuluq",
  "Landşaft bağçılığı",
  "Layihənin idarə olunması",
  "Logistika və nəqliyyat texnologiyaları mühəndisliyi",
  "Makroiqtisadi siyasət",
  "Maldarlıq",
  "Maliyyə",
  "Maliyyə bazarları",
  "Maliyyə menecmenti",
  "Maliyyə nəzarəti və audit",
  "Mamalıq, ginekologiya və süni mayalanma",
  "Marketinq",
  "Maşın mühəndisliyi",
  "Maşın və aparat hissələrinin yeyilməyədavamlılığının yüksəldilməsi və bərpası texnologiyası və avadanlığı",
  "Maşın və mexanizmlər nəzəriyyəsi",
  "Maşınqayırma materialşünaslığı",
  "Maşınqayırma texnologiyası",
  "Maşınqayırmada kompüter texnologiyaları",
  "Materiallar mühəndisliyi",
  "Materialşünaslıq və materiallar texnologiyası",
  "Maye, qaz və plazma mexanikası",
  "Media və kommunikasiya sistemləri",
  "Mexanika",
  "Mexanika mühəndisliyi",
  "Mexatronika və robototexnika mühəndisliyi",
  "Meliorasiya- mühəndis sistemləri",
  "Meliorasiya mühəndisliyi",
  "Meliorasiya, rekultivasiya və torpaq",
  "Meliorasiya-mühəndis sistemləri",
  "Memarlıq",
  "Memarlıq abidələrinin bərpası və yenidən qurulması ",
  "Menecment",
  "Meşə əkinləri",
  "Meşə quruluşu",
  "Meşə taksasiyası",
  "Meşəçilik",
  "Metal konstruksiyaları",
  "Metalların təzyiq altında emalı",
  "Metalların və ərintilərin tökmə istehsalı",
  "Metallurgiya mühəndisliyi",
  "Metallurji tullantıların təkrar emal texnologiyaları",
  "Metalşünaslıq və metalların termiki emalı",
  "Metrologiya və metroloji təminat",
  "Meyvəçilik",
  "Mədən mühəndisliyi",
  "Mədəni antropologiya",
  "Mədəniyyətin nəzəriyyəsi",
  "Mədəniyyətin tarixi",
  "Məktəbəqədər təhsil",
  "Məktəbəqədər təlim və tərbiyənin metodika və metodologiyası",
  "Mikologiya",
  "Mıkologiya",
  "Mikrobiologiya",
  "Milli təhlükəsizlik və siyasi strategiya",
  "Mineralogiya",
  "Mobil tətbiqlərin hazırlanması və oyun dizaynı",
  "Molekulyar biologiya",
  "Musiqi fənninin tədrisi metodikası və metodologiyası",
  "Musiqi müəllimliyi",
  "Musiqi nəzəriyyəsi",
  "Musiqi tarixi",
  "Musiqi texnologiyaları",
  "Musiqi tənqidi",
  "Muzey, arxiv işi və abidələrin qorunması",
  "Muzeyşünaslıq",
  "Müasir danışıqlar təcrübəsi",
  "Müasir dövrdə Yaxın və Orta Şərq ölkələrinin xarici siyasəti",
  "Müəssisənin iqtisadiyyatı",
  "Mühasibat",
  "Mühasibat ■",
  "Mühəndis fizikası",
  "Mühəndis geologiyası",
  "Mülki və təsərrüfat hüququ",
  "Nanobiotexnologiya",
  "Nanomateriallar kimyası",
  "Neft emalı texnologiyası",
  "Neft kimyası",
  "Neft- qaz mühəndisliyi",
  "Neft və kimya sahəsində ətraf mühitin mühafizəsi",
  "Neft və qaz texnologiyası",
  "Neft və qaz yataqlarının işlənməsi",
  "Neft-qaz mühəndisliyi",
  "Neft-qaz yataqlarının axtarışı və kəşfiyyatının geofiziki üsulları",
  "Nəqliyyat ekologiyası",
  "Nəqliyyat xidmətləri üçün böhran və risklərin idarə edilməsi",
  "Nəqliyyat logistikası",
  "Nəqliyyat mühəndisliyi",
  "Nəqliyyat radio avadanlıqlarının texniki istismarı",
  "Nəqliyyat tikintisi mühəndisliyi",
  "Nəqliyyat vasitələrinin elektrik avadanlığı və elektronikası ",
  "Nəqliyyatda daşımalar və menecment",
  "Nəqliyyatda servis",
  "Nəşriyyat işi və redaktəetmə",
  "Nəzəri və riyazi fizika",
  "Onurğalılar zoologiyası",
  "Onurğasızlar zoologiyası",
  "Operator sənəti",
  "Optik-elektron cihazlar və sistemləri",
  "Optimal idarəetmənin riyazi-iqtisadi üsulları",
  "Optimal idarəetmənin riyazi-iqtisadı üsulları",
  "Optimallaşdırma və optimal idarəetmə",
  "Optotexnika mühəndisliyi",
  "Orta əsrlər tarixi",
  "Otelçilik",
  "Otelçılik",
  "Ölkəşünaslıq",
  "Parazitologiya və invazion xəstəliklər",
  "Pedaqogika nəzəriyyəsi və tarixi",
  "Pedaqoji psixologiya",
  "Petrologiya",
  "Pirotexniki və partladım vasitələr mühəndisliyi",
  "Polimerlərin kimyəvi texnologiyası",
  "Politologiya",
  "Populyar musiqi və caz ifaçılığı",
  "Proseslərin avtomatlaşdırılması mühəndisliyi",
  "Psixologiya",
  "Publisistik jurnalistika",
  "Rabitə qovşaqları və kommutasiya",
  "Radiasiya materialşünaslığı",
  "Radıoelektron mübarizə vasitələri",
  "Radiotexnika və telekommunikasiya mühəndisliyi",
  "Radiotelejumalistika",
  "Regional idarəetmə",
  "Regionşünaslıq",
  "Rejissor sənətinin tarixi və nəzəriyyəsi",
  "Rejissorluq",
  "Rəqəmsal hökumət",
  "Rəqs sənəti üzrə müəllim-tədqiqatçı",
  "Rəngkarlıq",
  "Riyazi analiz",
  "Riyaziyyat",
  "Riyaziyyat müəllimliyi",
  "Riyaziyyat və informatika müəllimliyi",
  "Riyaziyyatın tədrisi metodikası və metodologiyası",
  "Seysmologiya və seysmometriya",
  "Sənaye istilik energetikası",
  "Sənaye qurğuları və texnoloji komplekslərin avtomatikası və elektrik intiqalı",
  "Sənaye mikrobiologiyası",
  "Sənaye mühəndisliyi",
  "Sənəd resursları və informasiya-axtarış sistemləri",
  "Sənətşünaslıq",
  "Səyahət agentliyi və turoperator",
  "Sığorta işinin təşkili",
  "Silah və silah sistemləri mühəndisliyi",
  "Sinxron tərcümə",
  "Sistem proqramlaşdırılması",
  "Siyasi analiz və konsaltinq",
  "Slavyan ölkələri tarixi",
  "Solooxuma",
  "Sosial iş",
  "Sosial pedaqogika",
  "Sosial psixologiya",
  "Sosial-mədəni sahələrdə xidmətlərin təşkili",
  "Sosiologiya",
  "Soyuducu maşın və qurğular",
  "Ssenarist",
  "Standartlaşdırma və sertifikatlaşdırma",
  "Statistika",
  "Stomatologiya",
  "Strateji idarəetmə",
  "Su bioehtiyatları",
  "Su bioehtiyatları və akvakultura",
  "Su ehtiyatlarının inteqrasiyalı idarə",
  "Şəhərsalma",
  "Şərabçılıq",
  "Şərabçılıq və qıcqırtma istehsalının texnologiyası",
  "Tarix",
  "Tarix fənninin tədrisi metodikası və istifadəsi",
  "Tarix müəllimliyi",
  "Tarix və coğrafiya müəllimliyi",
  "Teatr tarixi və nəzəriyyəsi",
  "Teatr tənqidi",
  "Texniki sistemlərdə informatika və idarəetmə",
  "Texnologiya fənninin tədrisi",
  "Texnologiya müəllimliyi",
  "Texnoloji komplekslərin layihələndirilməsi",
  "Texnoloji proseslərin avtomatlaşdırılması və idarə edilməsi",
  "Texnoloji proseslərin və istehsalatın avtomatlaşdırılması",
  "Televiziya və radio yayımları",
  "Təbii ehtiyatların qorunması və təkrar emalı",
  "Təbii liflərin istehsalının texnologiyası və avadanlıqları",
  "Təbii və fizioloji fəal maddələr",
  "Təhsildə qiymətləndirmə və monitorinq",
  "Təhsildə sosial-psixoloji xidmət",
  "Tərcümə",
  "Tərəvəzçilik",
  "Təsviri incəsənət fənninin tədrisi",
  "Təsviri incəsənət müəllimliyi",
  "Təsviri incəsənət tarixi və nəzəriyyəsi",
  "Tətbiqi geodeziya",
  "Tətbiqi proqram təminatı",
  "Tibb",
  "Tibb bacısı işi",
  "Tibbi hüquq",
  "Tikiş məmulatlarının texnologiyası",
  "Torpağın aqroekoloji",
  "Torpaq kadastrı",
  "Torpaqşünaslıq",
  "Torpaqşünaslıq və aqrokimya",
  "Tökmə və qaynaq istehsalının maşın və avadanlıqları",
  "Transmilli cinayət hüququ",
  "Tribotexnika",
  "Turizm bələdçiliyi",
  "Turizm işi",
  "Turizm işinin təşkili",
  "Turizm və sosial-mədəni servis",
  "Turizmin bələdçisi",
  "Turizmin iqtisadiyyatı",
  "Türk dünyası tarixi",
  "Uçuş aparatları və güc qurğuları",
  "Uçuş aparatlarının elektrik, radio və cihaz avadanlıqları",
  "Uçuş mühəndisliyi",
  "Uşaq və yaş psixologiyası",
  "Ümumi psixologiya",
  "Üzümçülük",
  "Üzvi kimya",
  "Vergi və vergiqoyma",
  "Verilənlərin təhlili",
  "Vokal ifaçılığı",
  "Vokal ifaçılığının tarixi və nəzəriyyəsi",
  "Yaxın və Orta Şərqin tarixi",
  "Yanğın təhlükəsizliyi mühəndisliyi",
  "Yarımkeçirici cihazlar və mikroelektronıka",
  "Yarımkeçiricilər fizikası",
  "Yatağın qiymətləndirilməsi və idarə olunması",
  "Yer quruluşu və torpaq müfəttişliyi kadastrı",
  "Yerquruluşu və daşınmaz əmlakın",
  "Yol hərəkətinin təşkili və təhlükəsizliyi",
  "Yoluxmayan daxili xəstəliklər",
  "Yüksək gərginliklər texnikası və fizikası",
  "Yüksək molekullu birləşmələr kimyası",
  "Yüksəkmolekullu birləşmələr kimyası",
  "Zoomühəndislik",
];
